#pragma once

#include "gnc/sensors.hpp"
#include <Eigen/Dense>
#include <cmath>
#include <vector>

// ##### navigation, the big picture #####
// Goal: split "decide the aim point" from "steer at the current aim
// point" into two classes. Navigation is the path planner: given ONE
// final target, it lays out a straight-line sequence of nearby waypoints
// and walks a NavigationStep through them one at a time. NavigationStep
// is the actual per-tick controller -- point the nose at whatever target
// it's currently given, shaped by a PID per axis (pitch-plane, yaw-
// plane). Splitting them this way means NavigationStep only ever has to
// steer toward something a fixed, small distance away, so one PID gain
// set can cover both a target close to the pad and one far downrange --
// each step looks like the same kind of local steering problem.
namespace navigation {

// ##### NavigationStep #####
// Goal: point the nose at whatever target it's currently pointed at
// (see setTarget()), shaped by a PID per axis instead of commanding the
// raw angular error straight through. TVC's own actuator lag (see
// thrust_vector_control.hpp) models the physical servo -- it has no
// feedback loop of its own -- so this class is where the actual
// closed-loop control law lives: P reacts to how far off-target the nose
// is, I cleans up whatever P alone can't null out, D would react to the
// vehicle's own spin rate but is tuned to 0 by default (see the
// constructor).
//
// The PID doesn't read raw GPS -- it reads a FUSED position estimate
// (see estimatePosition()) blending the noisy GPS fix with the
// accelerometer's own double-integrated motion. Why: GPS's own noise has
// a ~60s correlation time, comparable to this vehicle's whole ~25s
// flight, so within one flight it looks less like jitter and more like a
// near-constant few-meter miscalibration -- no amount of PID retuning
// fixes that. The fused estimate is a real step up from raw GPS, though
// it can't invent an independent ground truth GPS doesn't have either.
//
// Stays neutral below ACTIVATION_ALTITUDE_M -- right off the pad, the
// rocket is slow and barely off vertical, so a tiny angle error would
// swing the PID command toward full gimbal deflection at exactly the
// wrong moment (rail/tower still nearby, no airspeed for TVC to matter
// yet anyway). This is also the only thing standing between this class
// and steering toward a low aim point while genuinely close to the
// ground -- Navigation relies on that when it hands this class an early,
// low-altitude waypoint (see navigation.cpp).
class NavigationStep {
public:
    // Goal: fix the current aim point and gains, and size the
    // position-estimator gains once up front from the sim's own dt (see
    // estimatePosition()). Gains default to this project's own GA-tuned
    // values (src/tuning/); a caller can still override them.
    NavigationStep(const Eigen::Vector3d& target_position, double dt,
                   double kp = 2.7176, double ki = 1.8196, double kd = 0.0745);

    // Goal: retarget this controller -- Navigation calls this when it
    // advances to the next waypoint. No validation: waypoints are
    // generated by Navigation and trusted here, same as the ground
    // check moving out of this class's constructor (see class comment).
    void setTarget(const Eigen::Vector3d& target_position) { target_position_ = target_position; }

    // Goal: the one call site -- read the current sensors, decide which
    // way to steer, and hand back a body-frame direction for
    // ThrustVectorControl::commandForceDirection. Not const: the
    // integral accumulators and position filter are real memory that
    // persists step to step.
    Eigen::Vector3d computeTvcTarget(const sensors::Gps& gps, const sensors::Gyro& gyro, double dt);

    // Goal: expose the position filter's own latest estimate so
    // Navigation can tell how close the vehicle actually is to the
    // current waypoint, without duplicating this filter itself.
    Eigen::Vector3d lastEstimatedPosition() const { return fused_position_; }

private:
    static constexpr double ACTIVATION_ALTITUDE_M = 2.0;   // vehicle altitude before guidance activates

    // ##### PID gains #####
    // Goal: Kp=1, Ki=0, Kd=0 reproduces the old direct-passthrough
    // behavior exactly (a property of the formula in computeTvcTarget(),
    // true regardless of what the defaults below happen to be). The
    // defaults themselves came from src/tuning/'s genetic-algorithm
    // search, superseding an earlier manual grid search that had landed
    // on (1.0, 0.6, 0.0) -- see Staging Notes #15/#16 for how the GA
    // search works and its known caveats (a single fixed local-hop
    // scenario, no averaging across sensor-noise draws, etc.) before
    // trusting these three numbers as final. The SAME triple drives both
    // the pitch-plane and yaw-plane loops below (computeTvcTarget()) --
    // not one gain set per axis.
    // Stored as instance members (not static constexpr) so the GA gain
    // tuner (src/tuning/) can search over them.
    const double kp_;
    const double ki_;
    const double kd_;

    // Goal: cap how much the integral term alone can contribute, so a
    // long saturated stretch can't build more windup than one actuator
    // swing is worth. Mirrors ThrustVectorControl::MAX_GIMBAL_DEG as its
    // own constant (kept decoupled rather than shared, same pattern
    // sensors.cpp uses for its own ISA formula copy).
    static constexpr double MAX_GIMBAL_RAD = 30.0 * M_PI / 180.0;

    // ##### Position estimator (alpha-beta / g-h filter) #####
    // Goal: track position+velocity, predicting each step from the
    // accelerometer's own measured (noisy) acceleration rather than
    // assuming constant velocity the way a textbook alpha-beta filter
    // does, then correcting both from GPS's residual each step. Gains
    // are derived (Wikipedia's steady-state g-h relation, from this
    // project's own real sensor sigmas), not guessed. Horizontal (x,y)
    // and vertical (z) get separate gains since GPS's own noise differs
    // between them.
    static constexpr double GPS_HORIZONTAL_SIGMA_M = 2.5;
    static constexpr double GPS_VERTICAL_SIGMA_M = 2.5 * 1.7;
    static constexpr double ACCEL_NOISE_STD_MPS2 = 0.008 * 9.80665;

    static void computeAlphaBeta(double sigma_process, double sigma_meas, double dt,
                                  double& alpha, double& beta);
    Eigen::Vector3d estimatePosition(const sensors::Gps& gps, const sensors::Gyro& gyro,
                                      const Eigen::Matrix3d& R, double dt);

    double horizontal_alpha_;
    double horizontal_beta_;
    double vertical_alpha_;
    double vertical_beta_;

    Eigen::Vector3d fused_position_ = Eigen::Vector3d::Zero();
    Eigen::Vector3d fused_velocity_ = Eigen::Vector3d::Zero();
    bool position_filter_initialized_ = false;

    Eigen::Vector3d target_position_;  // world frame, meters -- current aim point

    // Integral accumulators, one per axis -- real memory between calls.
    double integral_pitch_ = 0.0;
    double integral_yaw_ = 0.0;
};

// ##### Navigation #####
// Goal: the path planner. Takes the ONE final target the rest of the
// codebase (main.cpp's --target, trajectory.py's GUI) ever talks about,
// and walks a NavigationStep through a straight-line sequence of nearby
// waypoints toward it instead of aiming at the far-off final target from
// step one. A stepping stone for a real curved path planner later --
// today's planner always optimizes for shortest distance (a line).
class Navigation {
public:
    // Goal: fix the real target for the whole flight (validated here --
    // see NavigationStep's class comment for why the ground check lives
    // here and not there), lay out the waypoint list, and construct the
    // per-tick controller aimed at the first one. Gains are forwarded to
    // NavigationStep unchanged; a caller that omits them gets today's
    // tuned defaults.
    Navigation(const Eigen::Vector3d& final_target, double dt,
               double kp = 2.7176, double ki = 1.8196, double kd = 0.0745);

    // Goal: the one call site RocketKinematics::simulate() uses --
    // drives the current waypoint's NavigationStep, then advances to the
    // next waypoint once close enough.
    Eigen::Vector3d computeTvcTarget(const sensors::Gps& gps, const sensors::Gyro& gyro, double dt);

    // Goal: let a caller (main.cpp's console log, the GA tuner) confirm
    // how many waypoints a given target actually produced.
    size_t waypointCount() const { return waypoints_.size(); }

    // Goal: expose which waypoint is currently active -- lets a caller
    // tell "reached the last waypoint" apart from "got stuck on an
    // earlier one because it never entered WAYPOINT_ARRIVAL_RADIUS_M."
    size_t currentWaypointIndex() const { return current_waypoint_idx_; }

private:
    static constexpr double MIN_TARGET_ALTITUDE_M = 10.0;   // ground-safety floor, meters
    static constexpr double WAYPOINT_STEP_M = 50.0;         // straight-line spacing between waypoints
    // "close enough, advance" radius. A miss here isn't fatal -- see the
    // path-direction fallback in computeTvcTarget() -- but a bigger
    // radius still means an earlier, gentler advance for a real target.
    static constexpr double WAYPOINT_ARRIVAL_RADIUS_M = 2.0;

    std::vector<Eigen::Vector3d> waypoints_;
    size_t current_waypoint_idx_ = 0;
    NavigationStep step_;

    // Goal: the path's own straight-line direction, set once at
    // construction -- lets computeTvcTarget() tell "flew past this
    // waypoint" from "still approaching it" even when it never actually
    // enters WAYPOINT_ARRIVAL_RADIUS_M (see computeTvcTarget()'s own
    // comment for why that fallback exists).
    Eigen::Vector3d direction_;
};

}  // namespace navigation
